import type { City, Guide, Place, Itinerary, Interest, TrendingExperience } from "../types";

export const CITIES: City[] = [
  {
    id: "Astana",
    name: "Astana",
    country: "Kazakhstan",
    safetyScore: 92,
    popularityScore: 88,
    imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
  },
  {
    id: "Almaty",
    name: "Almaty",
    country: "Kazakhstan",
    safetyScore: 89,
    popularityScore: 95,
    imageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=800",
  },
  {
    id: "Aktau",
    name: "Aktau",
    country: "Kazakhstan",
    safetyScore: 87,
    popularityScore: 72,
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800",
  },
];

export const INTERESTS: Interest[] = [
  { id: "food", label: "Food & Dining", icon: "restaurant" },
  { id: "culture", label: "Culture & History", icon: "book" },
  { id: "nightlife", label: "Nightlife", icon: "wine" },
  { id: "nature", label: "Nature & Parks", icon: "leaf" },
  { id: "adventure", label: "Adventure", icon: "compass" },
  { id: "shopping", label: "Shopping", icon: "bag-handle" },
  { id: "photography", label: "Photography", icon: "camera" },
  { id: "wellness", label: "Wellness", icon: "fitness" },
  { id: "family", label: "Family Friendly", icon: "people" },
  { id: "budget", label: "Budget Travel", icon: "wallet" },
  { id: "luxury", label: "Luxury", icon: "diamond" },
  { id: "local", label: "Local Experiences", icon: "people-outline" },
];

export const GUIDES: Guide[] = [
  {
    id: "1",
    name: "Aibek Nurlan",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    rating: 4.9,
    reviewCount: 247,
    verified: true,
    pricePerHour: 8500,
    currency: "₸",
    tags: ["History", "Architecture", "Local Food"],
    bio: "Born and raised in Almaty. I love showing visitors the hidden gems and stories behind every street. 10+ years guiding experience.",
    languages: ["Kazakh", "Russian", "English"],
    specialties: ["City Tours", "Food Tours", "Photography Walks"],
    heroImageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=800",
    toursCompleted: 412,
    responseTime: "< 1 hour",
    experienceYears: 10,
    tourPackages: [
      { id: "p1", title: "Almaty Highlights", duration: "4h", price: 34000, currency: "₸", description: "Best of Almaty in one day" },
      { id: "p2", title: "Food & Bazaar", duration: "3h", price: 25500, currency: "₸", description: "Green Bazaar & local tastings" },
    ],
    whatsappNumber: "77001234567",
  },
  {
    id: "2",
    name: "Dana Serikova",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    rating: 4.8,
    reviewCount: 189,
    verified: true,
    pricePerHour: 7200,
    currency: "₸",
    tags: ["Nature", "Hiking", "Photography"],
    bio: "Mountain lover and certified hiking guide. Kok Tobe, Medeu, and beyond. Let's find the best views together.",
    languages: ["Russian", "English"],
    specialties: ["Mountain Tours", "Sunset Views", "Instagram Spots"],
    heroImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    toursCompleted: 298,
    responseTime: "< 2 hours",
    experienceYears: 6,
    tourPackages: [
      { id: "p3", title: "Kok Tobe Sunset", duration: "3h", price: 21600, currency: "₸", description: "Cable car & mountain views" },
      { id: "p4", title: "Medeu & Shymbulak", duration: "6h", price: 43200, currency: "₸", description: "Ice rink & ski resort" },
    ],
    whatsappNumber: "77001234568",
  },
  {
    id: "3",
    name: "Yerzhan Batyrov",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    rating: 4.7,
    reviewCount: 134,
    verified: true,
    pricePerHour: 6500,
    currency: "₸",
    tags: ["Astana", "Modern Architecture", "Nightlife"],
    bio: "Astana native. Expert in the new capital's architecture, parks, and the best spots for evening fun.",
    languages: ["Kazakh", "Russian", "English"],
    specialties: ["Architecture Tours", "Bayterek", "Khan Shatyr"],
    heroImageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
    toursCompleted: 221,
    responseTime: "< 1 hour",
    experienceYears: 5,
    tourPackages: [
      { id: "p5", title: "Astana in a Day", duration: "5h", price: 32500, currency: "₸", description: "Bayterek, Nur-Astana Mosque, Expo" },
    ],
    whatsappNumber: "77001234569",
  },
  {
    id: "4",
    name: "Aruzhan Ospanova",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    rating: 4.6,
    reviewCount: 67,
    verified: false,
    pricePerHour: 5500,
    currency: "₸",
    tags: ["Culture", "Museums", "Family"],
    bio: "Art historian and family-friendly guide. Museums, parks, and activities that kids love.",
    languages: ["Kazakh", "Russian"],
    specialties: ["Museum Tours", "Family Tours", "Cultural Walks"],
    heroImageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=800",
    toursCompleted: 89,
    responseTime: "< 3 hours",
    experienceYears: 3,
    tourPackages: [
      { id: "p6", title: "Museum Day", duration: "4h", price: 22000, currency: "₸", description: "Central State Museum & more" },
    ],
    whatsappNumber: "77001234570",
  },
  {
    id: "5",
    name: "Murat Zhanatayev",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    rating: 4.9,
    reviewCount: 312,
    verified: true,
    pricePerHour: 9000,
    currency: "₸",
    tags: ["Aktau", "Caspian", "Adventure"],
    bio: "Caspian coast specialist. Sherkala, beaches, and the unique landscape of Mangystau. Off-road and camping trips.",
    languages: ["Kazakh", "Russian", "English"],
    specialties: ["Caspian Tours", "Sherkala", "Desert Adventures"],
    heroImageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800",
    toursCompleted: 534,
    responseTime: "< 1 hour",
    experienceYears: 12,
    tourPackages: [
      { id: "p7", title: "Sherkala & Canyon", duration: "8h", price: 72000, currency: "₸", description: "Full day desert adventure" },
      { id: "p8", title: "Caspian Beach Day", duration: "5h", price: 45000, currency: "₸", description: "Beaches and local seafood" },
    ],
    whatsappNumber: "77001234571",
  },
];

export const PLACES: Place[] = [
  { id: "place-1", name: "Bayterek Tower", imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600", safetyScore: 96, rating: 4.8, tags: ["Landmark", "Views", "Astana"] },
  { id: "place-2", name: "Khan Shatyr", imageUrl: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600", safetyScore: 94, rating: 4.7, tags: ["Shopping", "Entertainment"] },
  { id: "place-3", name: "Hazrat Sultan Mosque", imageUrl: "https://images.unsplash.com/photo-1567596434663-f8c2d2e1e8a8?w=600", safetyScore: 98, rating: 4.9, tags: ["Architecture", "Culture"] },
  { id: "place-4", name: "Medeu Rink", imageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=600", safetyScore: 91, rating: 4.6, tags: ["Sports", "Nature", "Almaty"] },
  { id: "place-5", name: "Green Bazaar", imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600", safetyScore: 85, rating: 4.5, tags: ["Food", "Local", "Markets"] },
  { id: "place-6", name: "Kok Tobe", imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600", safetyScore: 92, rating: 4.8, tags: ["Views", "Cable Car", "Photo Spot"] },
  { id: "place-7", name: "Caspian Beach", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600", safetyScore: 88, rating: 4.4, tags: ["Beach", "Aktau", "Nature"] },
  { id: "place-8", name: "Sherkala Mountain", imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600", safetyScore: 82, rating: 4.9, tags: ["Adventure", "Desert", "Hiking"] },
];

const ALMATY_TIMELINE_STOPS = [
  { id: "s1", title: "Kok Tobe Cable Car Station", time: "18:30", imageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=600", safetyLevel: "safe" as const, safetyScore: 92, tags: ["Transport", "Landmark"], instaWorthy: true, visibility: "Clear", crowdLevel: "Moderate" },
  { id: "s2", title: "Cable Car Ride", time: "18:45", imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600", safetyLevel: "safe" as const, safetyScore: 95, tags: ["Experience"], aiNote: "Best views at sunset. Hold onto your phone for photos!", visibility: "Panoramic" },
  { id: "s3", title: "Observation Deck", time: "19:00", imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600", safetyLevel: "safe" as const, safetyScore: 94, tags: ["Views", "Photo"], instaWorthy: true, aiNote: "Golden hour here is incredible. City lights start around 19:45.", visibility: "Clear", crowdLevel: "High" },
  { id: "s4", title: "Walk to Restaurant", time: "19:30", imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600", safetyLevel: "safe" as const, safetyScore: 90, tags: ["Walking"], walkingTime: "5 min", walkingTerrain: "Paved path, well-lit" },
  { id: "s5", title: "Mountain Breeze Restaurant", time: "19:35", imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600", safetyLevel: "safe" as const, safetyScore: 93, tags: ["Dining", "Local Cuisine"], aiNote: "Try the lagman and shashlik. Reserve window seat for views.", crowdLevel: "Moderate" },
  { id: "s6", title: "Kok Tobe Park", time: "20:50", imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600", safetyLevel: "safe" as const, safetyScore: 91, tags: ["Park", "Evening"], instaWorthy: true, aiNote: "Ferris wheel and souvenir stalls. Safe and family-friendly.", visibility: "Good", crowdLevel: "Moderate" },
  { id: "s7", title: "Return Cable Car", time: "21:30", imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600", safetyLevel: "safe" as const, safetyScore: 94, tags: ["Transport"], walkingTime: "2 min", walkingTerrain: "Paved" },
  { id: "s8", title: "City Center", time: "21:45", imageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=600", safetyLevel: "safe" as const, safetyScore: 89, tags: ["Drop-off"], aiNote: "Taxis and ride-share available. Area is safe for evening strolls.", visibility: "Well-lit", crowdLevel: "Moderate" },
];

export const ALMATY_ITINERARY: Itinerary = {
  id: "itin-almaty-1",
  cityId: "almaty",
  cityName: "Almaty",
  title: "Kok Tobe Evening Experience",
  stops: ALMATY_TIMELINE_STOPS,
  totalSafetyScore: 92,
  totalDuration: "3h 15m",
  estimatedCost: "₸25,000 – 35,000",
  previewImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
  createdAt: new Date().toISOString(),
};

export const SAVED_TRIPS: Itinerary[] = [
  ALMATY_ITINERARY,
  {
    ...ALMATY_ITINERARY,
    id: "itin-almaty-2",
    title: "Green Bazaar & City Walk",
    previewImageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    totalSafetyScore: 88,
    totalDuration: "4h",
    estimatedCost: "₸15,000 – 20,000",
  },
];

export const TRENDING_EXPERIENCES: TrendingExperience[] = [
  { id: "t1", title: "Kok Tobe Sunset", imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400", safetyScore: 92, tags: ["Views", "Cable Car"] },
  { id: "t2", title: "Green Bazaar Tasting", imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=400", safetyScore: 85, tags: ["Food", "Local"] },
  { id: "t3", title: "Medeu Ice Rink", imageUrl: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=400", safetyScore: 91, tags: ["Sports", "Nature"] },
  { id: "t4", title: "Bayterek Tower", imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400", safetyScore: 96, tags: ["Landmark", "Astana"] },
];
